# frozen_string_literal: true

source 'https://rubygems.org'

gem 'deepl-rb', require: 'deepl'
gem 'dotenv', '~> 2.7'
gem 'middleman', '~> 4.5'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'nokogiri', '~> 1.18'
gem 'rubocop', '~> 1.80', require: false
gem 'terser', '~> 1.1'
gem 'tzinfo-data', platforms: %i[mswin mingw jruby x64_mingw]
gem 'wdm', '~> 0.1', platforms: %i[mswin mingw x64_mingw]
